<?php

namespace App\controllers;

use App\components\DBComponent;
use App\exceptions\RaptorException;

class Home extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}